version: '3.4'
services:
  nginx:
    image: nginx:latest@sha256:4ffd9758ea9ea360fd87d0cee7a2d1cf9dba630bb57ca36b3108dcd3708dc189
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/nginx/nginx.api.conf:/etc/nginx/conf.d/api.conf
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: default.Dockerfile
    container_name: api
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - GCLOUD_PROJECT=motor-cards-v3-workers
      - GOOGLE_APPLICATION_CREDENTIALS=./src/config/gcloud-servicekey.json
      - DATA_BACKEND=datastore
    ports:
      - 9229:9229
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src